--- 
framework: mocha
version: 1.0.0
postMerge: 
  pattern: 
    - "test/**/*.spec.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "test/**/*.spec.js"
preRun: 
  command: 
    - npm ci


